version: '3'
services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 3001:3000
    command: bash -c "npm install && node server.js"
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    command: bash -c "npm install && npm start"
