version: '3'
services:
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 3001:3000
    command: node server.js
  frontend:
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    command: npm start
